version: "3.7"
services:
  app:
    build:
      args:
        user: opc
        uid: 1000
      context: ./
      dockerfile: Dockerfile
    image: kuis2
    container_name: kuis2-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - kuis2

  db:
    image: mysql:5.7
    container_name: kuis2-db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USERNAME}
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    networks:
      - kuis2

  nginx:
    image: nginx:alpine
    container_name: kuis2-nginx
    restart: unless-stopped
    ports:
      - 80:80
    volumes:
      - ./:/var/www
      - ./docker-compose/nginx:/etc/nginx/conf.d/
    networks:
      - kuis2

networks:
  kuis2:
    driver: bridge